/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  hero_image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description: string;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: Block_content;
  order?: number;
  featured?: boolean;
};

export type Block_content = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  title?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  quote: string;
  rating?: number;
  featured?: boolean;
  order?: number;
};

export type Company = {
  _id: string;
  _type: "company";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  website?: string;
  featured?: boolean;
  order?: number;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  flyer: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  mode: "in_person" | "online" | "hybrid";
  starts_at: string;
  ends_at?: string;
  location?: {
    venue?: string;
    address?: string;
    city?: string;
    country?: string;
  };
  meeting_url?: string;
  entry: "free" | "paid" | "invite_only";
  slots_available?: number;
  description?: Block_content;
  featured?: boolean;
};

export type Gallery_albumReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "gallery_album";
};

export type Gallery = {
  _id: string;
  _type: "gallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  album: Gallery_albumReference;
  main_image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  more_images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
  excerpt?: string;
  description?: Block_content;
  size?: {
    heightCm?: number;
    widthCm?: number;
    depthCm?: number;
    notes?: string;
  };
  created_at?: string;
  price?: {
    currency?: "NGN" | "USD" | "GBP" | "EUR";
    amount?: number;
  };
  availability: "available" | "sold" | "not_for_sale";
  featured?: boolean;
};

export type Gallery_album = {
  _id: string;
  _type: "gallery_album";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  featured?: boolean;
};

export type Post_category = {
  _id: string;
  _type: "post_category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post_categoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post_category";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  author?: AuthorReference;
  main_image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  excerpt?: string;
  categories?: Array<
    {
      _key: string;
    } & Post_categoryReference
  >;
  published_at?: string;
  body: Block_content;
  sidebar_images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
  related_posts?: Array<
    {
      _key: string;
    } & PostReference
  >;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Service
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Faq
  | Block_content
  | Testimonial
  | Company
  | Event
  | Gallery_albumReference
  | Gallery
  | Gallery_album
  | Post_category
  | AuthorReference
  | Post_categoryReference
  | PostReference
  | Post
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../src/builders/blog/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post"] | order(_createdAt desc) {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "excerpt": coalesce(excerpt, ""),  _createdAt,  _updatedAt,  author->{    _id,    "name": coalesce(name, ""),    "slug": coalesce(slug.current, ""),    "bio": coalesce(bio, ""),    image {      "url": coalesce(asset->url, null),      "alt": coalesce(alt, "")    }  },  "categories": coalesce(    categories[]->{      _id,      "title": coalesce(title, ""),      "slug": coalesce(slug.current, "")    },    []  ),  main_image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type AllPostsQueryResult = Array<{
  _id: string;
  _type: "post";
  title: string;
  slug: string;
  excerpt: string | "";
  _createdAt: string;
  _updatedAt: string;
  author: {
    _id: string;
    name: string | "";
    slug: string | "";
    bio:
      | Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>
      | "";
    image: {
      url: string | null;
      alt: "";
    } | null;
  } | null;
  categories:
    | Array<{
        _id: string;
        title: string | "";
        slug: string | "";
      }>
    | Array<never>;
  main_image: {
    url: string | null;
    alt: string;
  } | null;
}>;

// Source: ../src/builders/blog/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0] {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "excerpt": coalesce(excerpt, ""),  "body": coalesce(body, []),  _createdAt,  _updatedAt,  author->{    _id,    "name": coalesce(name, ""),    "slug": coalesce(slug.current, ""),    "bio": coalesce(bio, ""),    image {      "url": coalesce(asset->url, null),      "alt": coalesce(alt, "")    }  },  "categories": coalesce(    categories[]->{      _id,      "title": coalesce(title, ""),      "slug": coalesce(slug.current, "")    },    []  ),  main_image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type PostBySlugQueryResult = {
  _id: string;
  _type: "post";
  title: string;
  slug: string;
  excerpt: string | "";
  body: Block_content;
  _createdAt: string;
  _updatedAt: string;
  author: {
    _id: string;
    name: string | "";
    slug: string | "";
    bio:
      | Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>
      | "";
    image: {
      url: string | null;
      alt: "";
    } | null;
  } | null;
  categories:
    | Array<{
        _id: string;
        title: string | "";
        slug: string | "";
      }>
    | Array<never>;
  main_image: {
    url: string | null;
    alt: string;
  } | null;
} | null;

// Source: ../src/builders/blog/queries.ts
// Variable: allPostCategoriesQuery
// Query: *[_type == "post_category"] | order(title asc) {  _id,  _type,  "title": coalesce(title, ""),  "description": coalesce(description, "")}
export type AllPostCategoriesQueryResult = Array<{
  _id: string;
  _type: "post_category";
  title: string | "";
  description: string | "";
}>;

// Source: ../src/builders/blog/queries.ts
// Variable: postCategoryBySlugQuery
// Query: *[_type == "post_category" && slug.current == $slug][0] {  _id,  _type,  "title": coalesce(title, ""),  "description": coalesce(description, "")}
export type PostCategoryBySlugQueryResult = {
  _id: string;
  _type: "post_category";
  title: string | "";
  description: string | "";
} | null;

// Source: ../src/builders/blog/queries.ts
// Variable: allAuthorsQuery
// Query: *[_type == "author"] | order(name asc) {  _id,  _type,  "name": coalesce(name, ""),  "slug": coalesce(slug.current, ""),  "bio": coalesce(bio, ""),  image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type AllAuthorsQueryResult = Array<{
  _id: string;
  _type: "author";
  name: string | "";
  slug: string | "";
  bio:
    | Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>
    | "";
  image: {
    url: string | null;
    alt: "";
  } | null;
}>;

// Source: ../src/builders/blog/queries.ts
// Variable: authorBySlugQuery
// Query: *[_type == "author" && slug.current == $slug][0] {  _id,  _type,  "name": coalesce(name, ""),  "slug": coalesce(slug.current, ""),  "bio": coalesce(bio, ""),  image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }  }
export type AuthorBySlugQueryResult = {
  _id: string;
  _type: "author";
  name: string | "";
  slug: string | "";
  bio:
    | Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>
    | "";
  image: {
    url: string | null;
    alt: "";
  } | null;
} | null;

// Source: ../src/builders/blog/queries.ts
// Variable: recentPostsQuery
// Query: *[_type == "post"] | order(_createdAt desc) [0...$limit] {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "excerpt": coalesce(excerpt, ""),  _createdAt,  author->{    _id,    "name": coalesce(name, ""),    "slug": coalesce(slug.current, ""),    image {      "url": coalesce(asset->url, null),      "alt": coalesce(alt, "")    }  },  "categories": coalesce(    categories[]->{      _id,      "title": coalesce(title, ""),      "slug": coalesce(slug.current, "")    },    []  ),  main_image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type RecentPostsQueryResult = Array<{
  _id: string;
  _type: "post";
  title: string;
  slug: string;
  excerpt: string | "";
  _createdAt: string;
  author: {
    _id: string;
    name: string | "";
    slug: string | "";
    image: {
      url: string | null;
      alt: "";
    } | null;
  } | null;
  categories:
    | Array<{
        _id: string;
        title: string | "";
        slug: string | "";
      }>
    | Array<never>;
  main_image: {
    url: string | null;
    alt: string;
  } | null;
}>;

// Source: ../src/builders/blog/queries.ts
// Variable: postsByCategoryQuery
// Query: *[_type == "post" && $categoryId in categories[]._ref] | order(_createdAt desc) {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "excerpt": coalesce(excerpt, ""),  _createdAt,  author->{    _id,    "name": coalesce(name, ""),    "slug": coalesce(slug.current, ""),    image {      "url": coalesce(asset->url, null),      "alt": coalesce(alt, "")    }  },  "categories": coalesce(    categories[]->{      _id,      "title": coalesce(title, ""),      "slug": coalesce(slug.current, "")    },    []  ),  main_image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type PostsByCategoryQueryResult = Array<{
  _id: string;
  _type: "post";
  title: string;
  slug: string;
  excerpt: string | "";
  _createdAt: string;
  author: {
    _id: string;
    name: string | "";
    slug: string | "";
    image: {
      url: string | null;
      alt: "";
    } | null;
  } | null;
  categories:
    | Array<{
        _id: string;
        title: string | "";
        slug: string | "";
      }>
    | Array<never>;
  main_image: {
    url: string | null;
    alt: string;
  } | null;
}>;

// Source: ../src/builders/blog/queries.ts
// Variable: postsByAuthorQuery
// Query: *[_type == "post" && author._ref == $authorId] | order(_createdAt desc) {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "excerpt": coalesce(excerpt, ""),  _createdAt,  author->{    _id,    "name": coalesce(name, ""),    "slug": coalesce(slug.current, ""),    image {      "url": coalesce(asset->url, null),      "alt": coalesce(alt, "")    }  },  "categories": coalesce(    categories[]->{      _id,      "title": coalesce(title, ""),      "slug": coalesce(slug.current, "")    },    []  ),  main_image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type PostsByAuthorQueryResult = Array<{
  _id: string;
  _type: "post";
  title: string;
  slug: string;
  excerpt: string | "";
  _createdAt: string;
  author: {
    _id: string;
    name: string | "";
    slug: string | "";
    image: {
      url: string | null;
      alt: "";
    } | null;
  } | null;
  categories:
    | Array<{
        _id: string;
        title: string | "";
        slug: string | "";
      }>
    | Array<never>;
  main_image: {
    url: string | null;
    alt: string;
  } | null;
}>;

// Source: ../src/builders/gallery/queries.ts
// Variable: allGalleriesQuery
// Query: *[_type == "gallery"] | order(_createdAt desc)[0...10] {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "excerpt": coalesce(excerpt, ""),  "availability": coalesce(availability, ""),  featured,  created_at,  size {  "height": coalesce(heightCm, 0),  "width": coalesce(widthCm, 0),  "dept": coalesce(depthCm, 0),  "notes": coalesce(notes, "")  },  price {  "currency": coalesce(currency, "NGN"),  "amount": coalesce(amount, 0)  },  album->{    _id,    "title": coalesce(title, ""),    "slug": coalesce(slug.current, "")  },  main_image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  },  "more_images": coalesce(    more_images[] {      "url": coalesce(asset->url, null),      "alt": coalesce(alt, "")    },    []  )}
export type AllGalleriesQueryResult = Array<{
  _id: string;
  _type: "gallery";
  title: string;
  slug: string;
  excerpt: string | "";
  availability: "available" | "not_for_sale" | "sold";
  featured: boolean | null;
  created_at: string | null;
  size: {
    height: number | 0;
    width: number | 0;
    dept: number | 0;
    notes: string | "";
  } | null;
  price: {
    currency: "EUR" | "GBP" | "NGN" | "USD";
    amount: number | 0;
  } | null;
  album: {
    _id: string;
    title: string;
    slug: string;
  };
  main_image: {
    url: string | null;
    alt: string;
  };
  more_images:
    | Array<{
        url: string | null;
        alt: string;
      }>
    | Array<never>;
}>;

// Source: ../src/builders/gallery/queries.ts
// Variable: featuredGalleriesQuery
// Query: *[_type == "gallery" && featured == true] | order(_createdAt desc) {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "excerpt": coalesce(excerpt, ""),  "availability": coalesce(availability, ""),  "featured": coalesce(featured, false),  created_at,  size {  "height": coalesce(heightCm, 0),  "width": coalesce(widthCm, 0),  "dept": coalesce(depthCm, 0),  "notes": coalesce(notes, "")  },  price {  "currency": coalesce(currency, "NGN"),  "amount": coalesce(amount, 0)  },  album->{    _id,    "title": coalesce(title, ""),    "slug": coalesce(slug.current, ""),    "featured": coalesce(featured, false)  },  main_image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type FeaturedGalleriesQueryResult = Array<{
  _id: string;
  _type: "gallery";
  title: string;
  slug: string;
  excerpt: string | "";
  availability: "available" | "not_for_sale" | "sold";
  featured: boolean | false;
  created_at: string | null;
  size: {
    height: number | 0;
    width: number | 0;
    dept: number | 0;
    notes: string | "";
  } | null;
  price: {
    currency: "EUR" | "GBP" | "NGN" | "USD";
    amount: number | 0;
  } | null;
  album: {
    _id: string;
    title: string;
    slug: string;
    featured: boolean | false;
  };
  main_image: {
    url: string | null;
    alt: string;
  };
}>;

// Source: ../src/builders/gallery/queries.ts
// Variable: galleryBySlugQuery
// Query: *[_type == "gallery" && slug.current == $slug][0] {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "excerpt": coalesce(excerpt, ""),  "description": coalesce(description, ""),  "availability": coalesce(availability, ""),  "featured": coalesce(featured, false),  created_at,  "size": coalesce(size, ""),  "price": coalesce(price, 0),  album->{    _id,    "title": coalesce(title, ""),    "slug": coalesce(slug.current, "")  },  main_image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type GalleryBySlugQueryResult = {
  _id: string;
  _type: "gallery";
  title: string;
  slug: string;
  excerpt: string | "";
  description: Block_content | "";
  availability: "available" | "not_for_sale" | "sold";
  featured: boolean | false;
  created_at: string | null;
  size:
    | {
        heightCm?: number;
        widthCm?: number;
        depthCm?: number;
        notes?: string;
      }
    | "";
  price:
    | 0
    | {
        currency?: "EUR" | "GBP" | "NGN" | "USD";
        amount?: number;
      };
  album: {
    _id: string;
    title: string;
    slug: string;
  };
  main_image: {
    url: string | null;
    alt: string;
  };
} | null;

// Source: ../src/builders/gallery/queries.ts
// Variable: galleriesByAlbumQuery
// Query: *[_type == "gallery" && album._ref == $albumId] | order(_createdAt desc) {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "excerpt": coalesce(excerpt, ""),  "availability": coalesce(availability, ""),  "featured": coalesce(featured, false),  created_at,  "size": coalesce(size, ""),  "price": coalesce(price, 0),  album->{    _id,    "title": coalesce(title, ""),    "slug": coalesce(slug.current, "")  },  main_image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type GalleriesByAlbumQueryResult = Array<{
  _id: string;
  _type: "gallery";
  title: string;
  slug: string;
  excerpt: string | "";
  availability: "available" | "not_for_sale" | "sold";
  featured: boolean | false;
  created_at: string | null;
  size:
    | {
        heightCm?: number;
        widthCm?: number;
        depthCm?: number;
        notes?: string;
      }
    | "";
  price:
    | 0
    | {
        currency?: "EUR" | "GBP" | "NGN" | "USD";
        amount?: number;
      };
  album: {
    _id: string;
    title: string;
    slug: string;
  };
  main_image: {
    url: string | null;
    alt: string;
  };
}>;

// Source: ../src/builders/gallery/queries.ts
// Variable: allGalleryAlbumsQuery
// Query: *[_type == "gallery_album"] | order(title asc) {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "featured": coalesce(featured, false)}
export type AllGalleryAlbumsQueryResult = Array<{
  _id: string;
  _type: "gallery_album";
  title: string;
  slug: string;
  featured: boolean | false;
}>;

// Source: ../src/builders/gallery/queries.ts
// Variable: galleryAlbumBySlugQuery
// Query: *[_type == "gallery_album" && slug.current == $slug][0] {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "featured": coalesce(featured, false)}
export type GalleryAlbumBySlugQueryResult = {
  _id: string;
  _type: "gallery_album";
  title: string;
  slug: string;
  featured: boolean | false;
} | null;

// Source: ../src/builders/gallery/queries.ts
// Variable: availableGalleriesQuery
// Query: *[_type == "gallery" && availability == "available"] | order(_createdAt desc) {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "excerpt": coalesce(excerpt, ""),  "availability": coalesce(availability, ""),  "featured": coalesce(featured, false),  created_at,  "size": coalesce(size, ""),  "price": coalesce(price, 0),  album->{    _id,    "title": coalesce(title, ""),    "slug": coalesce(slug.current, ""),    "featured": coalesce(featured, false)  },  main_image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type AvailableGalleriesQueryResult = Array<{
  _id: string;
  _type: "gallery";
  title: string;
  slug: string;
  excerpt: string | "";
  availability: "available" | "not_for_sale" | "sold";
  featured: boolean | false;
  created_at: string | null;
  size:
    | {
        heightCm?: number;
        widthCm?: number;
        depthCm?: number;
        notes?: string;
      }
    | "";
  price:
    | 0
    | {
        currency?: "EUR" | "GBP" | "NGN" | "USD";
        amount?: number;
      };
  album: {
    _id: string;
    title: string;
    slug: string;
    featured: boolean | false;
  };
  main_image: {
    url: string | null;
    alt: string;
  };
}>;

// Source: ../src/builders/gallery/queries.ts
// Variable: albumsWithCountQuery
// Query: *[_type == "gallery_album"] | order(title asc) {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "featured": coalesce(featured, false),  "galleryCount": count(*[_type == "gallery" && references(^._id)])}
export type AlbumsWithCountQueryResult = Array<{
  _id: string;
  _type: "gallery_album";
  title: string;
  slug: string;
  featured: boolean | false;
  galleryCount: number;
}>;

// Source: ../src/builders/site/queries.ts
// Variable: allServicesQuery
// Query: *[_type == "service"] | order(order asc, _createdAt desc) {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "description": coalesce(description, ""),  "order": coalesce(order, 0),  "featured": coalesce(featured, false),  image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  },  hero_image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type AllServicesQueryResult = Array<{
  _id: string;
  _type: "service";
  title: string;
  slug: string;
  description: string;
  order: number | 0;
  featured: false;
  image: {
    url: string | null;
    alt: string;
  };
  hero_image: {
    url: string | null;
    alt: string | "";
  } | null;
}>;

// Source: ../src/builders/site/queries.ts
// Variable: allTestimonialsQuery
// Query: *[_type == "testimonial"] | order(_createdAt desc) {  _id,  _type,  "name": coalesce(name, ""),  "rating": coalesce(rating, 0),  "company": coalesce(company, ""),  "quote": coalesce(quote, ""),  avatar {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type AllTestimonialsQueryResult = Array<{
  _id: string;
  _type: "testimonial";
  name: string;
  rating: number | 0;
  company: "";
  quote: string;
  avatar: {
    url: string | null;
    alt: string;
  } | null;
}>;

// Source: ../src/builders/site/queries.ts
// Variable: allFaqsQuery
// Query: *[_type == "faq"] | order(order asc, _createdAt desc) {  _id,  _type,  "question": coalesce(question, ""),  "answer": coalesce(answer, ""),  "order": coalesce(order, 0),  "featured": coalesce(featured, false)}
export type AllFaqsQueryResult = Array<{
  _id: string;
  _type: "faq";
  question: string;
  answer: Block_content;
  order: number | 0;
  featured: boolean | false;
}>;

// Source: ../src/builders/site/queries.ts
// Variable: allEventsQuery
// Query: *[_type == "event"] | order(date desc) {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "description": coalesce(description, ""),  date,  "location": coalesce(location, ""),  image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type AllEventsQueryResult = Array<{
  _id: string;
  _type: "event";
  title: string;
  slug: string;
  description: Block_content | "";
  date: null;
  location:
    | {
        venue?: string;
        address?: string;
        city?: string;
        country?: string;
      }
    | "";
  image: null;
}>;

// Source: ../src/builders/site/queries.ts
// Variable: allCompaniesQuery
// Query: *[_type == "company"] | order(title asc) {  _id,  _type,  "title": coalesce(title, ""),  logo {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type AllCompaniesQueryResult = Array<{
  _id: string;
  _type: "company";
  title: "";
  logo: {
    url: string | null;
    alt: string;
  };
}>;

// Source: ../src/builders/site/queries.ts
// Variable: featuredServicesQuery
// Query: *[_type == "service" && featured == true] | order(order asc) {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "description": coalesce(description, ""),  "order": coalesce(order, 0),  "featured": coalesce(featured, false),   image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type FeaturedServicesQueryResult = Array<never>;

// Source: ../src/builders/site/queries.ts
// Variable: serviceBySlugQuery
// Query: *[_type == "service" && slug.current == $slug][0] {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "description": coalesce(description, ""),  "order": coalesce(order, 0),  "featured": coalesce(featured, false),   image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type ServiceBySlugQueryResult = {
  _id: string;
  _type: "service";
  title: string;
  slug: string;
  description: string;
  order: number | 0;
  featured: false;
  image: {
    url: string | null;
    alt: string;
  };
} | null;

// Source: ../src/builders/site/queries.ts
// Variable: featuredFaqsQuery
// Query: *[_type == "faq" && featured == true] | order(order asc) {  _id,  _type,  "question": coalesce(question, ""),  "answer": coalesce(answer, ""),  "order": coalesce(order, 0),  "featured": coalesce(featured, false)}
export type FeaturedFaqsQueryResult = Array<{
  _id: string;
  _type: "faq";
  question: string;
  answer: Block_content;
  order: number | 0;
  featured: boolean | false;
}>;

// Source: ../src/builders/site/queries.ts
// Variable: upcomingEventsQuery
// Query: *[_type == "event" && date >= $now] | order(date asc) {  _id,  _type,  "title": coalesce(title, ""),  "slug": coalesce(slug.current, ""),  "description": coalesce(description, ""),  date,  "location": coalesce(location, ""),   image {    "url": coalesce(asset->url, null),    "alt": coalesce(alt, "")  }}
export type UpcomingEventsQueryResult = Array<{
  _id: string;
  _type: "event";
  title: string;
  slug: string;
  description: Block_content | "";
  date: null;
  location:
    | {
        venue?: string;
        address?: string;
        city?: string;
        country?: string;
      }
    | "";
  image: null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "post"] | order(_createdAt desc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "excerpt": coalesce(excerpt, ""),\n  _createdAt,\n  _updatedAt,\n  author->{\n    _id,\n    "name": coalesce(name, ""),\n    "slug": coalesce(slug.current, ""),\n    "bio": coalesce(bio, ""),\n    image {\n      "url": coalesce(asset->url, null),\n      "alt": coalesce(alt, "")\n    }\n  },\n  "categories": coalesce(\n    categories[]->{\n      _id,\n      "title": coalesce(title, ""),\n      "slug": coalesce(slug.current, "")\n    },\n    []\n  ),\n  main_image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': AllPostsQueryResult;
    '*[_type == "post" && slug.current == $slug][0] {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "excerpt": coalesce(excerpt, ""),\n  "body": coalesce(body, []),\n  _createdAt,\n  _updatedAt,\n  author->{\n    _id,\n    "name": coalesce(name, ""),\n    "slug": coalesce(slug.current, ""),\n    "bio": coalesce(bio, ""),\n    image {\n      "url": coalesce(asset->url, null),\n      "alt": coalesce(alt, "")\n    }\n  },\n  "categories": coalesce(\n    categories[]->{\n      _id,\n      "title": coalesce(title, ""),\n      "slug": coalesce(slug.current, "")\n    },\n    []\n  ),\n  main_image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': PostBySlugQueryResult;
    '*[_type == "post_category"] | order(title asc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "description": coalesce(description, "")\n}': AllPostCategoriesQueryResult;
    '*[_type == "post_category" && slug.current == $slug][0] {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "description": coalesce(description, "")\n}': PostCategoryBySlugQueryResult;
    '*[_type == "author"] | order(name asc) {\n  _id,\n  _type,\n  "name": coalesce(name, ""),\n  "slug": coalesce(slug.current, ""),\n  "bio": coalesce(bio, ""),\n  image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': AllAuthorsQueryResult;
    '*[_type == "author" && slug.current == $slug][0] {\n  _id,\n  _type,\n  "name": coalesce(name, ""),\n  "slug": coalesce(slug.current, ""),\n  "bio": coalesce(bio, ""),\n  image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n  }': AuthorBySlugQueryResult;
    '*[_type == "post"] | order(_createdAt desc) [0...$limit] {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "excerpt": coalesce(excerpt, ""),\n  _createdAt,\n  author->{\n    _id,\n    "name": coalesce(name, ""),\n    "slug": coalesce(slug.current, ""),\n    image {\n      "url": coalesce(asset->url, null),\n      "alt": coalesce(alt, "")\n    }\n  },\n  "categories": coalesce(\n    categories[]->{\n      _id,\n      "title": coalesce(title, ""),\n      "slug": coalesce(slug.current, "")\n    },\n    []\n  ),\n  main_image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': RecentPostsQueryResult;
    '*[_type == "post" && $categoryId in categories[]._ref] | order(_createdAt desc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "excerpt": coalesce(excerpt, ""),\n  _createdAt,\n  author->{\n    _id,\n    "name": coalesce(name, ""),\n    "slug": coalesce(slug.current, ""),\n    image {\n      "url": coalesce(asset->url, null),\n      "alt": coalesce(alt, "")\n    }\n  },\n  "categories": coalesce(\n    categories[]->{\n      _id,\n      "title": coalesce(title, ""),\n      "slug": coalesce(slug.current, "")\n    },\n    []\n  ),\n  main_image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': PostsByCategoryQueryResult;
    '*[_type == "post" && author._ref == $authorId] | order(_createdAt desc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "excerpt": coalesce(excerpt, ""),\n  _createdAt,\n  author->{\n    _id,\n    "name": coalesce(name, ""),\n    "slug": coalesce(slug.current, ""),\n    image {\n      "url": coalesce(asset->url, null),\n      "alt": coalesce(alt, "")\n    }\n  },\n  "categories": coalesce(\n    categories[]->{\n      _id,\n      "title": coalesce(title, ""),\n      "slug": coalesce(slug.current, "")\n    },\n    []\n  ),\n  main_image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': PostsByAuthorQueryResult;
    '*[_type == "gallery"] | order(_createdAt desc)[0...10] {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "excerpt": coalesce(excerpt, ""),\n  "availability": coalesce(availability, ""),\n  featured,\n  created_at,\n  size {\n  "height": coalesce(heightCm, 0),\n  "width": coalesce(widthCm, 0),\n  "dept": coalesce(depthCm, 0),\n  "notes": coalesce(notes, "")\n  },\n  price {\n  "currency": coalesce(currency, "NGN"),\n  "amount": coalesce(amount, 0)\n  },\n  album->{\n    _id,\n    "title": coalesce(title, ""),\n    "slug": coalesce(slug.current, "")\n  },\n  main_image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  },\n  "more_images": coalesce(\n    more_images[] {\n      "url": coalesce(asset->url, null),\n      "alt": coalesce(alt, "")\n    },\n    []\n  )\n}': AllGalleriesQueryResult;
    '*[_type == "gallery" && featured == true] | order(_createdAt desc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "excerpt": coalesce(excerpt, ""),\n  "availability": coalesce(availability, ""),\n  "featured": coalesce(featured, false),\n  created_at,\n  size {\n  "height": coalesce(heightCm, 0),\n  "width": coalesce(widthCm, 0),\n  "dept": coalesce(depthCm, 0),\n  "notes": coalesce(notes, "")\n  },\n  price {\n  "currency": coalesce(currency, "NGN"),\n  "amount": coalesce(amount, 0)\n  },\n  album->{\n    _id,\n    "title": coalesce(title, ""),\n    "slug": coalesce(slug.current, ""),\n    "featured": coalesce(featured, false)\n  },\n  main_image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': FeaturedGalleriesQueryResult;
    '*[_type == "gallery" && slug.current == $slug][0] {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "excerpt": coalesce(excerpt, ""),\n  "description": coalesce(description, ""),\n  "availability": coalesce(availability, ""),\n  "featured": coalesce(featured, false),\n  created_at,\n  "size": coalesce(size, ""),\n  "price": coalesce(price, 0),\n  album->{\n    _id,\n    "title": coalesce(title, ""),\n    "slug": coalesce(slug.current, "")\n  },\n  main_image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': GalleryBySlugQueryResult;
    '*[_type == "gallery" && album._ref == $albumId] | order(_createdAt desc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "excerpt": coalesce(excerpt, ""),\n  "availability": coalesce(availability, ""),\n  "featured": coalesce(featured, false),\n  created_at,\n  "size": coalesce(size, ""),\n  "price": coalesce(price, 0),\n  album->{\n    _id,\n    "title": coalesce(title, ""),\n    "slug": coalesce(slug.current, "")\n  },\n  main_image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': GalleriesByAlbumQueryResult;
    '*[_type == "gallery_album"] | order(title asc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "featured": coalesce(featured, false)\n}': AllGalleryAlbumsQueryResult;
    '*[_type == "gallery_album" && slug.current == $slug][0] {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "featured": coalesce(featured, false)\n}': GalleryAlbumBySlugQueryResult;
    '*[_type == "gallery" && availability == "available"] | order(_createdAt desc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "excerpt": coalesce(excerpt, ""),\n  "availability": coalesce(availability, ""),\n  "featured": coalesce(featured, false),\n  created_at,\n  "size": coalesce(size, ""),\n  "price": coalesce(price, 0),\n  album->{\n    _id,\n    "title": coalesce(title, ""),\n    "slug": coalesce(slug.current, ""),\n    "featured": coalesce(featured, false)\n  },\n  main_image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': AvailableGalleriesQueryResult;
    '*[_type == "gallery_album"] | order(title asc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "featured": coalesce(featured, false),\n  "galleryCount": count(*[_type == "gallery" && references(^._id)])\n}': AlbumsWithCountQueryResult;
    '*[_type == "service"] | order(order asc, _createdAt desc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "description": coalesce(description, ""),\n  "order": coalesce(order, 0),\n  "featured": coalesce(featured, false),\n  image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  },\n  hero_image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': AllServicesQueryResult;
    '*[_type == "testimonial"] | order(_createdAt desc) {\n  _id,\n  _type,\n  "name": coalesce(name, ""),\n  "rating": coalesce(rating, 0),\n  "company": coalesce(company, ""),\n  "quote": coalesce(quote, ""),\n  avatar {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': AllTestimonialsQueryResult;
    '*[_type == "faq"] | order(order asc, _createdAt desc) {\n  _id,\n  _type,\n  "question": coalesce(question, ""),\n  "answer": coalesce(answer, ""),\n  "order": coalesce(order, 0),\n  "featured": coalesce(featured, false)\n}': AllFaqsQueryResult;
    '*[_type == "event"] | order(date desc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "description": coalesce(description, ""),\n  date,\n  "location": coalesce(location, ""),\n  image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': AllEventsQueryResult;
    '*[_type == "company"] | order(title asc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  logo {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': AllCompaniesQueryResult;
    '*[_type == "service" && featured == true] | order(order asc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "description": coalesce(description, ""),\n  "order": coalesce(order, 0),\n  "featured": coalesce(featured, false),\n   image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': FeaturedServicesQueryResult;
    '*[_type == "service" && slug.current == $slug][0] {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "description": coalesce(description, ""),\n  "order": coalesce(order, 0),\n  "featured": coalesce(featured, false),\n   image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': ServiceBySlugQueryResult;
    '*[_type == "faq" && featured == true] | order(order asc) {\n  _id,\n  _type,\n  "question": coalesce(question, ""),\n  "answer": coalesce(answer, ""),\n  "order": coalesce(order, 0),\n  "featured": coalesce(featured, false)\n}': FeaturedFaqsQueryResult;
    '*[_type == "event" && date >= $now] | order(date asc) {\n  _id,\n  _type,\n  "title": coalesce(title, ""),\n  "slug": coalesce(slug.current, ""),\n  "description": coalesce(description, ""),\n  date,\n  "location": coalesce(location, ""),\n   image {\n    "url": coalesce(asset->url, null),\n    "alt": coalesce(alt, "")\n  }\n}': UpcomingEventsQueryResult;
  }
}
